import { LigmaConfig } from "./scripts/utils/types";

export const config: LigmaConfig = {
    dsa: [
        "DFSOnBST",
        "LRU",
        "LinearSearchList",
        "BinarySearchList",
        "TwoCrystalBalls",
        "BubbleSort",
        "SinglyLinkedList",
        "DoublyLinkedList",
        "Queue",
        "Stack",
        "ArrayList",
        "MazeSolver",
        "QuickSort",
        "BTPreOrder",
        "BTInOrder",
        "BTPostOrder",
        "BTBFS",
        "CompareBinaryTrees",
        "DFSGraphList",
        "Trie",
        "BFSGraphMatrix",
        "BFSGraphList",
        "Map",
        "MinHeap",
        "DijkstraList",
        "InsertionSort",
        "MergeSort",
        "RingBuffer",
        "PrimsList",
        "BinarySearchTree",
        "AVLTree",
        "BTree",
        "UnionFind",
        "IndexedMinHeap",
        "TopologicalSort",
        "KruskalList",
        "FordFulkerson",
        "Factorial",
        "Fibonacci",
        "MaxSubarray",
        "CoinChange",
        "BloomFilter",
    ],
};
